### PR TITLE
Fix acronym between two letters

### PR DESCRIPTION
**Pull request by RamonGilabert**

### CODE REVIEW

**Comment by RamonGilabert** [comment]
Basically: https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/issues/11

**Comment by RamonGilabert** [comment]
Now it should pass everything! The code is a bit sketchy, it can be improved, but as we're using scanner to check the string, that makes it a bit more difficult to fix this problem!

**Comment by 3lvis** [comment]
The implementation looks very good and easy to understand :star2: :hamburger: :star2: !!!

**Comment by RamonGilabert** [comment]
Oh nice! :) And all is well! :yum:

**Pull request merged**
